[project]
name = "yadb-python-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aioodbc>=0.5.0",
    "fastapi[standard]>=0.115.4",
    "pyodbc>=5.2.0",
]
